run-name: Build SpaceLabs by @${{ github.actor }}
concurrency: build-${{ github.sha }}

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  run_test:
    name: Run Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: jacoco-result
          folder: ./target/site/jacoco